### ISSUE TITLE
Effectuer des tests avec la limelight pour trouver un pipeline de vision qui permet de détecter efficacement les notes

### ISSUE THREAD

**Issue by Andlat** [hyperion-3360/2024-crescendo#14]

**Comment by shdalton** [comment]
LimeLight up and running configured with static IP 10.33.60.11. The reason for not being able to connect was a bad Ethernet cable

**Comment by Andlat** [comment]
**HSV thresholds with Microsoft LifeCam 3000**
min: [0, 120, 200]
max: [30, 255, 255]
